# exclude: .*migrations\/.*
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.0'
    hooks:
      - id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        # args: ["--force-exclude", --line-length, "120"]
        args: [ "--line-length", "120" ]

  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
        args: [ --line-length=120 ]

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        exclude: migrations

  - repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
      - id: pip-compile
